### ISSUE TITLE
Defining groupings

### ISSUE THREAD

**Issue by DominikSchmidtlein** [erickadbay/smartlibrary#25]
We still don't have a satisfactory solution for defining what belongs to which grouping.

This include
* creating groupings
* deleting groupings
* adding desk/grouping to grouping
* removing desk/grouping from grouping
* changing grouping name
* moving desk/grouping from grouping to another

I can't picture how this would work? Maybe a simple form with drop down lists where possible?

**Comment by MikeVezina** [comment]
Up for further debate, but the drop down lists aren't such a bad idea. There should be a location in the admin UI where an admin can manage the list of groupings. 

When adding / modifying a specific desk, the admin may choose the grouping of that desk based on the listing.
